# Generated by Django 6.0.3 on 2026-03-16 13:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('signals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decided_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('decision', models.CharField(choices=[('YES', 'Yes (took it)'), ('NO', 'No (passed)'), ('SKIP', 'Skip/Other')], max_length=8)),
                ('notes', models.TextField(blank=True)),
                ('outcome', models.CharField(choices=[('UNKNOWN', 'Unknown'), ('WIN', 'Win'), ('LOSS', 'Loss'), ('BREAKEVEN', 'Breakeven')], default='UNKNOWN', max_length=16)),
                ('realized_r', models.DecimalField(blank=True, decimal_places=2, help_text='Optional: realized R-multiple', max_digits=8, null=True)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('signal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='signals.signal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-decided_at',),
            },
        ),
    ]
