# Generated by Django 6.0.3 on 2026-03-16 13:26

import apps.portfolios.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketdata', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountRetentionPolicyTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_label', models.CharField(blank=True, default='', max_length=80)),
                ('template_name', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('evidence_retention_default_days', models.PositiveIntegerField(blank=True, null=True)),
                ('evidence_retention_verified_days', models.PositiveIntegerField(blank=True, null=True)),
                ('evidence_retention_strong_days', models.PositiveIntegerField(blank=True, null=True)),
                ('evidence_retention_weak_days', models.PositiveIntegerField(blank=True, null=True)),
                ('evidence_retention_placeholder_days', models.PositiveIntegerField(blank=True, null=True)),
                ('evidence_retention_confirmation_days', models.PositiveIntegerField(blank=True, null=True)),
                ('evidence_retention_import_match_days', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_retention_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('family_label', 'template_name'),
            },
        ),
        migrations.CreateModel(
            name='AccountRetentionPolicyOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_label', models.CharField(max_length=80)),
                ('evidence_retention_default_days', models.PositiveIntegerField(blank=True, null=True)),
                ('evidence_retention_verified_days', models.PositiveIntegerField(blank=True, null=True)),
                ('evidence_retention_strong_days', models.PositiveIntegerField(blank=True, null=True)),
                ('evidence_retention_weak_days', models.PositiveIntegerField(blank=True, null=True)),
                ('evidence_retention_placeholder_days', models.PositiveIntegerField(blank=True, null=True)),
                ('evidence_retention_confirmation_days', models.PositiveIntegerField(blank=True, null=True)),
                ('evidence_retention_import_match_days', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_retention_overrides', to=settings.AUTH_USER_MODEL)),
                ('source_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seeded_overrides', to='portfolios.accountretentionpolicytemplate')),
            ],
            options={
                'ordering': ('account_label',),
            },
        ),
        migrations.CreateModel(
            name='BrokerPositionImportRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_label', models.CharField(default='Broker CSV', max_length=80)),
                ('account_label', models.CharField(blank=True, default='', max_length=80)),
                ('uploaded_filename', models.CharField(blank=True, max_length=255)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('preview_rows', models.JSONField(blank=True, default=list)),
                ('unresolved_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broker_position_import_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='HeldPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=16)),
                ('source', models.CharField(choices=[('MANUAL', 'Manual entry'), ('IMPORT', 'Import')], default='MANUAL', max_length=16)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=20)),
                ('average_entry_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('stop_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('target_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('thesis', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('last_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('last_price_at', models.DateTimeField(blank=True, null=True)),
                ('pnl_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('pnl_pct', models.FloatField(blank=True, null=True)),
                ('close_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('close_notes', models.TextField(blank=True)),
                ('account_label', models.CharField(blank=True, default='', max_length=80)),
                ('last_import_seen_at', models.DateTimeField(blank=True, null=True)),
                ('missing_from_latest_import', models.BooleanField(default=False)),
                ('reconciliation_note', models.TextField(blank=True)),
                ('reconciliation_resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='held_positions', to='marketdata.instrument')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='held_positions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BrokerPositionImportResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=32)),
                ('action', models.CharField(choices=[('REVIEWED_OK', 'Reviewed and acceptable'), ('CLOSE_TRACKED', 'Close tracked holding'), ('ADD_TRACKED', 'Add tracked holding'), ('QUANTITY_ACCEPTED', 'Quantity difference accepted'), ('FOLLOW_UP', 'Manual follow-up')], max_length=24)),
                ('note', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broker_position_import_resolutions', to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolutions', to='portfolios.brokerpositionimportrun')),
                ('tracked_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broker_import_resolutions', to='portfolios.heldposition')),
            ],
            options={
                'ordering': ('-resolved_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='HoldingAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('STOP_BREACH', 'Stop breach'), ('THESIS_BREAK', 'Thesis break'), ('DETERIORATING', 'Deteriorating'), ('TARGET_REACHED', 'Target reached')], max_length=24)),
                ('channel', models.CharField(choices=[('DISCORD', 'Discord'), ('EMAIL', 'Email')], max_length=16)),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped'), ('DRY_RUN', 'Dry run')], max_length=16)),
                ('reason', models.CharField(blank=True, max_length=64)),
                ('message', models.TextField(blank=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('payload_snapshot', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='portfolios.heldposition')),
            ],
        ),
        migrations.CreateModel(
            name='HoldingTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('OPEN', 'Open'), ('IMPORT_SYNC', 'Import sync'), ('BUY_ADD', 'Add shares'), ('PARTIAL_SELL', 'Partial sell'), ('CLOSE', 'Close'), ('ACCOUNT_TRANSFER', 'Move / relabel account')], max_length=24)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=20)),
                ('price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('account_label_snapshot', models.CharField(blank=True, default='', max_length=80)),
                ('stop_price_snapshot', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('risk_guardrail_posture_snapshot', models.CharField(blank=True, default='', max_length=16)),
                ('risk_guardrail_reason_snapshot', models.CharField(blank=True, default='', max_length=120)),
                ('stop_policy_due_at', models.DateTimeField(blank=True, null=True)),
                ('stop_policy_resolved_at', models.DateTimeField(blank=True, null=True)),
                ('stop_policy_status', models.CharField(blank=True, default='', max_length=16)),
                ('stop_policy_reason_code', models.CharField(blank=True, default='', max_length=32)),
                ('stop_policy_note', models.TextField(blank=True)),
                ('execution_evidence_type', models.CharField(blank=True, default='', max_length=32)),
                ('execution_evidence_quality', models.CharField(blank=True, default='', max_length=20)),
                ('execution_evidence_reference', models.CharField(blank=True, default='', max_length=120)),
                ('execution_evidence_note', models.TextField(blank=True)),
                ('execution_evidence_recorded_at', models.DateTimeField(blank=True, null=True)),
                ('execution_evidence_attachment', models.FileField(blank=True, null=True, upload_to=apps.portfolios.models.holding_transaction_evidence_upload_to)),
                ('execution_evidence_retention_until', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('realized_pnl_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='portfolios.heldposition')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ImportedBrokerSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_label', models.CharField(default='Broker CSV', max_length=80)),
                ('account_label', models.CharField(blank=True, default='', max_length=80)),
                ('as_of', models.DateTimeField(default=django.utils.timezone.now)),
                ('account_equity', models.DecimalField(decimal_places=2, max_digits=20)),
                ('cash_balance', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broker_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-as_of', '-id'),
            },
        ),
        migrations.CreateModel(
            name='SavedFilterPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('SIGNALS', 'Signals'), ('HOLDINGS', 'Holdings')], max_length=16)),
                ('name', models.CharField(max_length=100)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('is_dashboard_widget', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_filter_presets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('scope', 'name'),
            },
        ),
        migrations.CreateModel(
            name='UserRiskProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_equity', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('risk_per_trade_pct', models.DecimalField(decimal_places=4, default=0.0025, max_digits=6)),
                ('max_position_weight_pct', models.DecimalField(decimal_places=2, default=20, max_digits=6)),
                ('max_sector_weight_pct', models.DecimalField(decimal_places=2, default=35, max_digits=6)),
                ('concentration_warning_buffer_pct', models.DecimalField(decimal_places=2, default=5, max_digits=6)),
                ('max_high_correlation_positions', models.PositiveIntegerField(default=2)),
                ('high_correlation_threshold', models.DecimalField(decimal_places=2, default=0.8, max_digits=4)),
                ('correlation_lookback_bars', models.PositiveIntegerField(default=60)),
                ('max_net_exposure_pct', models.DecimalField(decimal_places=2, default=80, max_digits=6)),
                ('net_exposure_warning_buffer_pct', models.DecimalField(decimal_places=2, default=10, max_digits=6)),
                ('require_stop_for_open_positions', models.BooleanField(default=True)),
                ('max_stop_loss_pct', models.DecimalField(decimal_places=2, default=8, max_digits=6)),
                ('stop_warning_buffer_pct', models.DecimalField(decimal_places=2, default=1.5, max_digits=6)),
                ('drawdown_review_pct', models.DecimalField(decimal_places=2, default=2.5, max_digits=6)),
                ('drawdown_urgent_pct', models.DecimalField(decimal_places=2, default=5.0, max_digits=6)),
                ('stop_policy_target_hours', models.PositiveIntegerField(default=24)),
                ('evidence_retention_default_days', models.PositiveIntegerField(default=365)),
                ('evidence_retention_verified_days', models.PositiveIntegerField(default=730)),
                ('evidence_retention_strong_days', models.PositiveIntegerField(default=365)),
                ('evidence_retention_weak_days', models.PositiveIntegerField(default=180)),
                ('evidence_retention_placeholder_days', models.PositiveIntegerField(default=90)),
                ('evidence_retention_confirmation_days', models.PositiveIntegerField(default=730)),
                ('evidence_retention_import_match_days', models.PositiveIntegerField(default=365)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default', max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High priority')], default='NORMAL', max_length=16)),
                ('sector', models.CharField(blank=True, default='', max_length=80)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketdata.instrument')),
                ('watchlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='portfolios.watchlist')),
            ],
        ),
        migrations.AddIndex(
            model_name='accountretentionpolicytemplate',
            index=models.Index(fields=['user', 'family_label', 'template_name'], name='idx_retention_template_family'),
        ),
        migrations.AddConstraint(
            model_name='accountretentionpolicytemplate',
            constraint=models.UniqueConstraint(fields=('user', 'template_name'), name='uniq_account_retention_template_name'),
        ),
        migrations.AddIndex(
            model_name='accountretentionpolicyoverride',
            index=models.Index(fields=['user', 'account_label'], name='idx_retention_override_account'),
        ),
        migrations.AddConstraint(
            model_name='accountretentionpolicyoverride',
            constraint=models.UniqueConstraint(fields=('user', 'account_label'), name='uniq_account_retention_override'),
        ),
        migrations.AddIndex(
            model_name='brokerpositionimportrun',
            index=models.Index(fields=['user', '-created_at'], name='idx_brokerrun_user_recent'),
        ),
        migrations.AddIndex(
            model_name='heldposition',
            index=models.Index(fields=['user', 'status', '-updated_at'], name='idx_hold_user_status'),
        ),
        migrations.AddIndex(
            model_name='heldposition',
            index=models.Index(fields=['instrument', 'status'], name='idx_hold_inst_status'),
        ),
        migrations.AddIndex(
            model_name='heldposition',
            index=models.Index(fields=['user', 'status', 'missing_from_latest_import'], name='idx_hold_import_gap'),
        ),
        migrations.AddIndex(
            model_name='heldposition',
            index=models.Index(fields=['user', 'account_label', 'status'], name='idx_hold_user_account'),
        ),
        migrations.AddIndex(
            model_name='brokerpositionimportresolution',
            index=models.Index(fields=['run', 'symbol'], name='idx_brokerres_run_symbol'),
        ),
        migrations.AddIndex(
            model_name='brokerpositionimportresolution',
            index=models.Index(fields=['user', '-resolved_at'], name='idx_brokerres_user_recent'),
        ),
        migrations.AlterUniqueTogether(
            name='brokerpositionimportresolution',
            unique_together={('run', 'symbol')},
        ),
        migrations.AddIndex(
            model_name='holdingalert',
            index=models.Index(fields=['position', 'alert_type', 'channel', '-created_at'], name='idx_holdalert_recent'),
        ),
        migrations.AddIndex(
            model_name='holdingtransaction',
            index=models.Index(fields=['position', '-created_at'], name='idx_holdtxn_recent'),
        ),
        migrations.AddIndex(
            model_name='importedbrokersnapshot',
            index=models.Index(fields=['user', '-as_of'], name='idx_brokersnap_user_asof'),
        ),
        migrations.AddIndex(
            model_name='savedfilterpreset',
            index=models.Index(fields=['user', 'scope', 'name'], name='idx_filterpreset_scope'),
        ),
        migrations.AlterUniqueTogether(
            name='savedfilterpreset',
            unique_together={('user', 'scope', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='watchlist',
            unique_together={('user', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='instrumentselection',
            unique_together={('watchlist', 'instrument')},
        ),
    ]
