# Generated by Django 6.0.3 on 2026-03-16 13:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceLifecycleAutomationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive_expired', models.BooleanField(default=False)),
                ('scanned_count', models.PositiveIntegerField(default=0)),
                ('attachment_count', models.PositiveIntegerField(default=0)),
                ('expiring_soon_count', models.PositiveIntegerField(default=0)),
                ('expired_count', models.PositiveIntegerField(default=0)),
                ('missing_retention_count', models.PositiveIntegerField(default=0)),
                ('archived_count', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_lifecycle_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['user', '-created_at'], name='idx_ev_lifecycle_recent')],
            },
        ),
    ]
