# Generated by Django 6.0.1 on 2026-03-26 14:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def _drop_stale_equity_transaction_table(apps, schema_editor):
    vendor = schema_editor.connection.vendor
    if vendor == "postgresql":
        schema_editor.execute(
            "DROP TABLE IF EXISTS stock_trader.portfolios_equitytransaction CASCADE; "
            "DROP TABLE IF EXISTS public.portfolios_equitytransaction CASCADE;"
        )
    else:
        schema_editor.execute("DROP TABLE IF EXISTS portfolios_equitytransaction")


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0004_portfoliohealthsnapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Drop any stale table left by a previous failed migration attempt.
        migrations.RunPython(
            code=_drop_stale_equity_transaction_table,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.CreateModel(
            name='EquityTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal')], max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('notes', models.TextField(blank=True)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equity_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='idx_equity_tx_user_ts')],
            },
        ),
    ]
