# Generated by Django 6.0.3 on 2026-03-16 13:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketdata', '0001_initial'),
        ('strategies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('DELIVERY_HEALTH', 'Delivery health'), ('DELIVERY_RECOVERY', 'Delivery recovery')], default='DELIVERY_HEALTH', max_length=32)),
                ('channel', models.CharField(choices=[('DISCORD', 'Discord'), ('EMAIL', 'Email')], max_length=16)),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped'), ('DRY_RUN', 'Dry run')], max_length=16)),
                ('reason', models.CharField(blank=True, max_length=64)),
                ('headline', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('payload_snapshot', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['kind', 'channel', 'status', '-created_at'], name='idx_opnotif_kind_ct')],
            },
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeframe', models.CharField(default='1m', max_length=8)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('direction', models.CharField(choices=[('LONG', 'Long'), ('SHORT', 'Short'), ('FLAT', 'Flat')], max_length=8)),
                ('signal_kind', models.CharField(choices=[('EVENT', 'Event'), ('STATE', 'State')], default='EVENT', max_length=16)),
                ('signal_label', models.CharField(blank=True, max_length=32)),
                ('score', models.FloatField(blank=True, null=True)),
                ('score_components', models.JSONField(blank=True, default=dict)),
                ('rationale', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('REVIEWED', 'Reviewed'), ('TAKEN', 'Taken'), ('SKIPPED', 'Skipped'), ('CLOSED_WIN', 'Closed win'), ('CLOSED_LOSS', 'Closed loss'), ('CONFIRMED', 'Confirmed'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('ARCHIVED', 'Archived')], default='NEW', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signals_created', to=settings.AUTH_USER_MODEL)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='marketdata.instrument')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='strategies.strategy')),
            ],
        ),
        migrations.CreateModel(
            name='PaperTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=16)),
                ('lifecycle_stage', models.CharField(choices=[('NEW', 'New'), ('ACTIVE', 'Active'), ('TARGET_1', 'Target 1 hit'), ('TARGET_2', 'Target 2 hit'), ('STOP_RISK', 'Stop risk'), ('EXIT_READY', 'Exit ready'), ('CLOSED', 'Closed')], default='NEW', max_length=16)),
                ('entry_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('entry_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('risk_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('pnl_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('pnl_pct', models.FloatField(blank=True, null=True)),
                ('target_1_hit', models.BooleanField(default=False)),
                ('target_2_hit', models.BooleanField(default=False)),
                ('stop_triggered', models.BooleanField(default=False)),
                ('active_stop_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('active_target_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('trailing_stop_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('highest_price_seen', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('lowest_price_seen', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('last_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('last_price_at', models.DateTimeField(blank=True, null=True)),
                ('closed_reason', models.CharField(blank=True, choices=[('MANUAL', 'Manual'), ('STOP', 'Stop'), ('TARGET_2', 'Target 2'), ('REVERSAL', 'Reversal'), ('OTHER', 'Other')], max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paper_trades', to=settings.AUTH_USER_MODEL)),
                ('signal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paper_trade', to='signals.signal')),
            ],
        ),
        migrations.CreateModel(
            name='AlertDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('DISCORD', 'Discord'), ('EMAIL', 'Email')], default='DISCORD', max_length=16)),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped'), ('DRY_RUN', 'Dry run')], max_length=16)),
                ('reason', models.CharField(blank=True, max_length=64)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('payload_snapshot', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('signal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_deliveries', to='signals.signal')),
            ],
        ),
        migrations.CreateModel(
            name='SignalOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('EVALUATED', 'Evaluated'), ('INSUFFICIENT', 'Insufficient bars')], default='PENDING', max_length=16)),
                ('outcome_label', models.CharField(blank=True, choices=[('WIN', 'Win'), ('LOSS', 'Loss'), ('MIXED', 'Mixed'), ('OPEN', 'Open'), ('AMBIGUOUS', 'Ambiguous'), ('FLAT', 'Flat')], max_length=16)),
                ('lookahead_bars', models.PositiveIntegerField(default=5)),
                ('bars_observed', models.PositiveIntegerField(default=0)),
                ('reference_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('return_pct', models.FloatField(blank=True, null=True)),
                ('max_favorable_excursion_pct', models.FloatField(blank=True, null=True)),
                ('max_adverse_excursion_pct', models.FloatField(blank=True, null=True)),
                ('target_1_hit', models.BooleanField(default=False)),
                ('target_2_hit', models.BooleanField(default=False)),
                ('stop_hit', models.BooleanField(default=False)),
                ('evaluation_notes', models.TextField(blank=True)),
                ('evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('signal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='outcome', to='signals.signal')),
            ],
        ),
        migrations.CreateModel(
            name='TradePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('stop_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('target_1', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('target_2', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('account_equity', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('risk_per_trade_pct', models.DecimalField(decimal_places=4, default=0.0025, max_digits=6)),
                ('suggested_qty', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('signal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trade_plan', to='signals.signal')),
            ],
        ),
        migrations.CreateModel(
            name='PositionAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('DETERIORATING', 'Deteriorating'), ('STOP_APPROACHING', 'Stop approaching'), ('TREND_REVERSAL', 'Trend reversal')], max_length=32)),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped'), ('DRY_RUN', 'Dry run')], max_length=16)),
                ('reason', models.CharField(blank=True, max_length=64)),
                ('payload_snapshot', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paper_trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_alerts', to='signals.papertrade')),
            ],
            options={
                'indexes': [models.Index(fields=['alert_type', 'status', '-created_at'], name='idx_posalert_type_stat_ct')],
            },
        ),
        migrations.AddIndex(
            model_name='signal',
            index=models.Index(fields=['-generated_at'], name='idx_signal_generated_at'),
        ),
        migrations.AddIndex(
            model_name='signal',
            index=models.Index(fields=['instrument', 'strategy'], name='idx_signal_inst_strategy'),
        ),
        migrations.AddIndex(
            model_name='signal',
            index=models.Index(fields=['signal_kind', 'signal_label'], name='idx_signal_kind_label'),
        ),
        migrations.AddIndex(
            model_name='papertrade',
            index=models.Index(fields=['status', '-updated_at'], name='idx_ptrade_status_upd'),
        ),
        migrations.AddIndex(
            model_name='alertdelivery',
            index=models.Index(fields=['channel', 'status', '-created_at'], name='idx_alert_chan_stat_ct'),
        ),
        migrations.AddIndex(
            model_name='signaloutcome',
            index=models.Index(fields=['status', '-updated_at'], name='idx_sigout_status_upd'),
        ),
        migrations.AddIndex(
            model_name='signaloutcome',
            index=models.Index(fields=['outcome_label', '-evaluated_at'], name='idx_sigout_label_eval'),
        ),
    ]
