# Generated by Django 6.0.3 on 2026-03-18 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatornotification',
            name='kind',
            field=models.CharField(choices=[('DELIVERY_HEALTH', 'Delivery health'), ('DELIVERY_RECOVERY', 'Delivery recovery'), ('PORTFOLIO_HEALTH', 'Portfolio health')], default='DELIVERY_HEALTH', max_length=32),
        ),
    ]
