# Generated by Django 6.0.3 on 2026-03-23 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0005_signal_user_status_created_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatornotification',
            name='kind',
            field=models.CharField(choices=[('DELIVERY_HEALTH', 'Delivery health'), ('DELIVERY_RECOVERY', 'Delivery recovery'), ('DAILY_ALERT_DIGEST', 'Daily alert digest'), ('PORTFOLIO_HEALTH', 'Portfolio health'), ('SCHEDULER_FAILURE', 'Scheduler failure')], default='DELIVERY_HEALTH', max_length=32),
        ),
    ]
