# Generated by Django 6.0.3 on 2026-03-16 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('asset_class', models.CharField(choices=[('STOCK', 'Stock'), ('CRYPTO', 'Crypto')], max_length=16)),
                ('exchange', models.CharField(blank=True, max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PriceBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeframe', models.CharField(choices=[('1m', '1m'), ('5m', '5m'), ('1d', '1d')], max_length=4)),
                ('ts', models.DateTimeField(help_text='Bar timestamp (end time) in UTC')),
                ('open', models.DecimalField(decimal_places=8, max_digits=20)),
                ('high', models.DecimalField(decimal_places=8, max_digits=20)),
                ('low', models.DecimalField(decimal_places=8, max_digits=20)),
                ('close', models.DecimalField(decimal_places=8, max_digits=20)),
                ('volume', models.DecimalField(decimal_places=8, max_digits=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_bars', to='marketdata.instrument')),
            ],
            options={
                'indexes': [models.Index(fields=['instrument', 'timeframe', '-ts'], name='idx_bar_instrument_tf_ts')],
                'constraints': [models.UniqueConstraint(fields=('instrument', 'timeframe', 'ts'), name='uniq_bar_instrument_tf_ts')],
            },
        ),
    ]
